### ISSUE TITLE
USER STORY: Hide outdated polls automatically

### ISSUE THREAD

**Issue by MichelleDuda** [MichelleDuda/love-running#4]
As a **website administrator**, I can **pick the expiry date while publishing a poll** so that **I can automatically hide the poll after a set time**.

### **Acceptance Criteria:** ###
- Acceptance Criteria 1: The poll should disappear after 11:59 PM on the target date. 
- Acceptance Criteria 2: The real estate of the poll should be reserved on the home page. A message that says "Stay tuned, a new poll is coming soon" should appear if no other Poll is active.
- Acceptance Criteria 3: The expiry date should be at least 3 days after the current date. 

### **Tasks** ###
- [ ] Update the admin module view: the poll design to include date picker.
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon."
- [ ] Create a Javascript function to validate the expiry date is at least after 3 days. 
- [ ] Create a job to check expired Polls everyday at 11:50PM and hide them accordingly. 
- [ ] Update the controller function.
- [ ] Update unit test scripts.
- [ ] Test the functionality.
